Repository chartjs/chartjs-plugin-zoom, pull requests merged in 2021-01, with the labels that each got.

#416 Remove Bower
  .gitignore
  MAINTAINING.md
  README.md
  gulpfile.js
  scripts/release.sh
Labels: chore

#414 Add an ESM build
  .gitignore
  gulpfile.js
  karma.conf.js
  package.json
  rollup.config.js
  src/index.esm.js
  src/index.js
  src/plugin.js
Labels: enhancement

#420 Add compressed-size action
  .github/workflows/compressed-size.yml
Labels: infrastructure

#419 Add release-drafter and publish-npm workflows
  .github/release-drafter.yml
  .github/workflows/publish-npm.yml
  .github/workflows/release-drafter.yml
  .npmignore
  .travis.yml
  MAINTAINING.md
  package.json
  scripts/release.sh
Labels: infrastructure

#421 Remove gulp, update deps, use chartjs-test-utils
  .eslintrc.yml
  gulpfile.js
  karma.conf.js
  package-lock.json
  package.json
  test/fixture.js
  test/index.js
  test/matchers.js
  test/plugins.js
  test/utils.js
Labels: infrastructure
