Repository chartjs/chartjs-plugin-zoom, pull requests merged in 2021-04, with the labels that each got.

#443 Update Chart.js dependency to 3.0.0
  README.md
  package-lock.json
  package.json
  test/fixtures/pan/category-x.png
Labels: dependencies, documentation

#451 Remove animationDuration option
  README.md
  samples/zoom-time.html
  src/plugin.js
  types/options.d.ts
Labels: bug

#453 Update dependencies, switch to eslint on .md
  .eslintrc.yml
  package-lock.json
  package.json
Labels: dependencies, infrastructure

#452 Refactor to logical entities
  .eslintrc.yml
  samples/.eslintrc.yml
  src/core.js
  src/hammer.js
  src/handlers.js
  src/plugin.js
  src/scale.types.js
  src/utils.js
  test/fixtures/pan/category-x.js
  test/fixtures/pan/category-x.png
  test/index.js
  test/specs/module.spec.js
  test/specs/zoom.spec.js
Labels: chore

#454 Use fallback configration for scale types
  src/core.js
  src/scale.types.js
Labels: chore

#455 Refactor startHammer
  src/hammer.js
  src/plugin.js
Labels: bug, chore

#457 Internal state handling
  src/core.js
  src/hammer.js
  src/handlers.js
  src/plugin.js
  src/scale.types.js
  src/state.js
  src/utils.js
  test/fixtures/zoom/drag.js
  test/fixtures/zoom/drag.png
Labels: enhancement

#459 Update README
  README.md
Labels: documentation

#461 Changes zoom.threshold default to 0
  docs/guide/options.md
Labels: documentation

#463 Correct zoom modifierKey docs
  docs/guide/options.md
Labels: documentation

#462 Add sample on time scale
  docs/.vuepress/config.js
  docs/samples/time.md
  docs/scripts/register.js
  docs/scripts/utils.js
  package-lock.json
  package.json
  samples/zoom-time.html
Labels: documentation

#464 Refactor & export pan and zoom functions
  docs/.vuepress/config.js
  docs/samples/api.md
  package-lock.json
  package.json
  src/core.js
  src/hammer.js
  src/handlers.js
  src/index.esm.js
  src/plugin.js
  src/utils.js
  types/index.d.ts
  types/options.d.ts
  types/tests/exports.ts
Labels: enhancement

#465 Bump version to 1.0.0-beta.2
  package-lock.json
  package.json
Labels: chore

#467 Fix minor typo errors in docs
  docs/guide/integration.md
  docs/guide/options.md
Labels: documentation

#469 Add missing return types
  types/index.d.ts
Labels: types

#472 Fix hook parameters
  src/core.js
  src/hammer.js
Labels: bug

#470 Combine range options, add minimum scale range
  docs/guide/options.md
  docs/samples/basic.md
  docs/samples/log.md
  src/core.js
  src/hammer.js
  src/handlers.js
  src/plugin.js
  src/scale.types.js
  types/index.d.ts
  types/options.d.ts
  types/tests/exports.ts
Labels: breaking change, enhancement

#473 Bump version to beta.3
  package-lock.json
  package.json
Labels: chore

#474 Use static offsets for panning rounded time scale
  karma.conf.js
  src/core.js
  src/hammer.js
  src/scale.types.js
  src/state.js
  test/fixtures/pan/time-day-left.js
  test/fixtures/pan/time-day-left.png
  test/fixtures/pan/time-day-right.js
  test/fixtures/pan/time-day-right.png
Labels: bug

#475 Add a sample for drag-to-zoom in docs
  docs/.vuepress/config.js
  docs/samples/drag.md
Labels: documentation

#481 Expose zoomFunctions and panFunctions for customization
  src/plugin.js
  test/specs/module.spec.js
Labels: enhancement

#476 Fix category panning
  docs/guide/options.md
  package-lock.json
  package.json
  src/core.js
  src/plugin.js
  src/scale.types.js
  test/fixtures/pan/category-x-1.js
  test/fixtures/pan/category-x-1.png
  test/fixtures/pan/category-x-10.js
  test/fixtures/pan/category-x-10.png
  test/fixtures/pan/category-x-25.js
  test/fixtures/pan/category-x-25.png
  test/fixtures/pan/category-x-5.js
  test/fixtures/pan/category-x-5.png
  test/fixtures/pan/category-x-50.js
  test/fixtures/pan/category-x-50.png
  test/fixtures/pan/category-x.png
  test/specs/defaults.spec.js
  types/options.d.ts
Labels: breaking change, bug

#477 Add API documentation (typedoc)
  .gitignore
  docs/.vuepress/config.js
  package-lock.json
  package.json
  tsconfig.json
Labels: documentation

#478 Add zoomScale, rename doPan to pan, doZoom to zoom
  docs/samples/api.md
  docs/samples/time.md
  docs/scripts/utils.js
  src/core.js
  src/hammer.js
  src/handlers.js
  src/index.esm.js
  src/plugin.js
  src/scale.types.js
  types/index.d.ts
  types/tests/exports.ts
Labels: breaking change, enhancement

#482 Bump version to 1.0.0-beta.4
  package-lock.json
  package.json
Labels: chore

#483 Make resetZoom accept UpdateMode argument
  src/plugin.js
Labels: enhancement
