Repository chartjs/chartjs-plugin-zoom, pull requests merged in 2021-03, with the labels that each got.

#428 Changes script URLs for chart.js and hammer in order to use node_modules
  samples/pan-bar.html
  samples/zoom-bar-x.html
  samples/zoom-bar.html
  samples/zoom-horizontal-bar.html
  samples/zoom-log.html
  samples/zoom-time.html
  samples/zoom.html
Labels: documentation

#433 Update actions, dependencies, etc
  .editorconfig
  .eslintrc.yml
  .github/workflows/ci.yml
  karma.conf.js
  package-lock.json
  package.json
  rollup.config.js
  samples/.eslintrc.yml
  samples/pan-bar.html
  samples/zoom-bar-x.html
  samples/zoom-bar.html
  samples/zoom-horizontal-bar.html
  samples/zoom-log.html
  samples/zoom-time.html
  samples/zoom.html
  src/plugin.js
  test/.eslintrc.yml
  test/index.js
  test/specs/defaults.spec.js
  test/specs/module.spec.js
  test/specs/zoom.spec.js
Labels: infrastructure

#434 Fix zoom on category scale
  karma.conf.js
  samples/zoom-bar-x.html
  src/plugin.js
Labels: bug

#429 Fix non-zoomable charts eating scroll events
  .eslintrc.yml
  src/plugin.js
Labels: bug

#437 Add tests, fix readme issues
  README.md
  karma.conf.js
  package-lock.json
  package.json
  src/plugin.js
  test/.eslintrc.yml
  test/fixtures/pan/category-x.js
  test/fixtures/pan/category-x.png
  test/fixtures/zoom/category-x.js
  test/fixtures/zoom/category-x.png
  test/fixtures/zoom/zoom-reset.js
  test/fixtures/zoom/zoom-reset.png
  test/index.js
  test/specs/defaults.spec.js
  test/specs/module.spec.js
  test/specs/pan.spec.js
  test/specs/zoom.spec.js
Labels: chore, documentation, infrastructure

#438 adding typings for Zoom analog to chartjs-plugin-annotation
  package-lock.json
  package.json
  types/index.d.ts
  types/options.d.ts
  types/test/exports.ts
  types/test/tsconfig.json
Labels: types

#439 Reuse types from Chart.ts
  types/options.d.ts
Labels: types

#440 Update docs, enhance linting, fix errors
  .markdownlint.yml
  CONTRIBUTING.md
  LICENSE.md
  README.md
  package-lock.json
  package.json
  src/plugin.js
  tsconfig.json
Labels: documentation, infrastructure

#399 Feature: Zoom each scale separately
  README.md
  samples/zoom-separately.html
  src/plugin.js
  test/specs/zoom.spec.js
Labels: enhancement
