Repository chartjs/chartjs-plugin-zoom, pull requests merged in 2021-05, with the labels that each got.

#486 Add click-to-zoom example
  docs/.vuepress/config.js
  docs/samples/click-zoom.md
  src/hammer.js
Labels: documentation

#485 Fix calling of onZoomComplete from wheel event
  src/handlers.js
  src/utils.js
  test/specs/zoom.spec.js
Labels: bug

#484 Drag-to-zoom: filter clicks and pan.modifierKey
  docs/samples/drag.md
  src/handlers.js
  src/plugin.js
  test/index.js
  test/specs/zoom.spec.js
Labels: bug, enhancement

#487 Add onPanStart and onZoomStart callbacks
  docs/.vuepress/config.js
  docs/guide/options.md
  docs/samples/click-zoom.md
  docs/samples/pan-region.md
  src/hammer.js
  src/handlers.js
  src/plugin.js
  test/specs/pan.spec.js
  test/specs/zoom.spec.js
  types/options.d.ts
Labels: enhancement

#488 Fix drag-zoom and pan for non-linear scales
  docs/.vuepress/config.js
  docs/samples/drag/category.md
  docs/samples/drag/linear.md
  docs/samples/drag/log.md
  docs/samples/drag/time.md
  docs/samples/drag/timeseries.md
  docs/samples/wheel/category.md
  docs/samples/wheel/click-zoom.md
  docs/samples/wheel/log.md
  docs/samples/wheel/over-scale-mode.md
  docs/samples/wheel/time.md
  docs/scripts/utils.js
  package-lock.json
  src/core.js
  src/handlers.js
  src/scale.types.js
  test/specs/api.spec.js
  test/specs/zoom.spec.js
  types/tests/exports.ts
Labels: bug, chore

#490 Bump version to 1.0.0-beta.5
  package-lock.json
  package.json
Labels: chore

#494 Fix delta calculation at direction change
  src/core.js
  src/scale.types.js
  test/fixtures/pan/category-x-5.png
  test/specs/pan.spec.js
Labels: bug

#495 Cancel all chart events while panning or dragging
  src/plugin.js
Labels: bug

#502 Add missing modifierKey properties to Options
  types/options.d.ts
Labels: bug, types

#507 Add the ability to enable both wheel and drag modes at the same time
  docs/guide/options.md
  docs/guide/usage.md
  docs/samples/basic.md
  docs/samples/drag/category.md
  docs/samples/drag/linear.md
  docs/samples/drag/log.md
  docs/samples/drag/time.md
  docs/samples/drag/timeseries.md
  docs/samples/pan-region.md
  docs/samples/wheel/category.md
  docs/samples/wheel/click-zoom.md
  docs/samples/wheel/log.md
  docs/samples/wheel/over-scale-mode.md
  docs/samples/wheel/time.md
  samples/zoom-separately.html
  src/hammer.js
  src/handlers.js
  src/plugin.js
  test/fixtures/zoom/category-x.js
  test/fixtures/zoom/drag.js
  test/fixtures/zoom/zoom-reset.js
  test/specs/defaults.spec.js
  test/specs/zoom.spec.js
  types/options.d.ts
  types/tests/exports.ts
Labels: breaking change, enhancement

#512 Fix drag threshold for single axis modes
  src/handlers.js
Labels: bug

#513 Bump version to 1.0.0-rc, update dependencies
  package-lock.json
  package.json
Labels: chore

#518 Bump version to 1.0, update dependencies
  package-lock.json
  package.json
  test/fixtures/zoom/category-x.png
Labels: chore
