Repository chartjs/chartjs-plugin-zoom, pull requests merged in 2021-06, with the labels that each got.

#527 Fix: drag below threshold left dragging state on
  src/handlers.js
Labels: bug

#526 Fix: modifierKey is not required to end panning
  src/hammer.js
Labels: bug

#528 Bump version to 1.0.1, update dependencies
  package-lock.json
  package.json
Labels: dependencies

#531 Add .gitignore from Chart.js
  .gitignore
Labels: infrastructure

#524 Multi-axis zoom and original zoom limits
  docs/guide/options.md
  src/core.js
  src/hammer.js
  src/scale.types.js
  types/options.d.ts
Labels: enhancement

#534 Documentation and type definitions for zoomFunctions and panFunctions
  docs/.vuepress/config.js
  docs/guide/developers.md
  types/index.d.ts
Labels: documentation, types

#544 Fix errors from zero-dimension scales
  src/scale.types.js
  test/specs/pan.spec.js
Labels: bug

#547 Fix click to zoom sample
  docs/samples/wheel/click-zoom.md
Labels: documentation

#536 Add getZoomLevel function
  docs/samples/basic.md
  src/core.js
  src/plugin.js
  src/scale.types.js
  types/index.d.ts
Labels: enhancement

#553 Fix resetZoom after manual scale limits update
  src/core.js
  src/scale.types.js
  src/state.js
  test/fixtures/zoom/update-reset.js
  test/fixtures/zoom/update-reset.png
Labels: bug

#554 Update dependencies
  package-lock.json
  package.json
Labels: dependencies
