Repository chartjs/chartjs-plugin-zoom, pull requests merged in 2024-11, with the labels that each got.

#822 More descriptive types for Hammer.js events
  package-lock.json
  package.json
  types/options.d.ts
  types/tests/exports.ts
Labels: types

#784 fix: typo in drag options documentation
  docs/guide/options.md
Labels: documentation

#857 chore: update deps
  package-lock.json
  package.json
Labels: dependencies

#856 fix: explicit passive: false for wheel events to prevent warnings on console
  src/handlers.js
Labels: bug

#780 Add a function for getting zoom range
  docs/guide/developers.md
  src/core.js
  src/plugin.js
  test/specs/api.spec.js
  types/index.d.ts
Labels: enhancement

#811 Fix zoom outside of chart area
  src/handlers.js
Labels: bug

#862 chore: build cleanup, include homepage
  package-lock.json
  package.json
  rollup.config.js
Labels: chore

#863 fix: enabling pan after chart initialization
  .eslintrc.yml
  docs/.vuepress/config.js
  docs/samples/fetch-data.md
  docs/samples/pan/region.md
  docs/samples/pan/toggle.md
  package-lock.json
  package.json
  src/hammer.js
  src/plugin.js
Labels: bug

#864 fix: wheel zoom on logarighmic scale
  src/scale.types.js
  test/specs/api.spec.js
  test/specs/fixtures.spec.js
  test/specs/pan.spec.js
  test/specs/zoom.drag.spec.js
  test/specs/zoom.spec.js
  test/specs/zoom.wheel.spec.js
Labels: bug

#873 chore: add sample for minRange on category scale
  docs/.vuepress/config.js
  docs/samples/wheel/category-min-range.md
Labels: documentation

#885 chore: split ci to more steps
  .github/workflows/ci.yml
  package.json
Labels: chore

#886 chore: update actions to use node 20
  .github/workflows/ci.yml
  .github/workflows/documentation.yml
  .github/workflows/publish-npm.yml
Labels: infrastructure

#861 feat(drag): maintainAspectRatio
  docs/.vuepress/config.js
  docs/guide/options.md
  docs/samples/drag/linear-ratio.md
  src/handlers.js
  src/plugin.js
  test/specs/zoom.wheel.spec.js
Labels: enhancement

#887 chore: update some devdeps
  package-lock.json
  package.json
Labels: dependencies

#888 fix: incorrect zoom out factor when using using wheel
  docs/samples/api.md
  docs/samples/wheel/log.md
  karma.conf.js
  src/handlers.js
  src/scale.types.js
  test/specs/zoom.wheel.spec.js
Labels: bug

#889 fix: trigger onZoom from zoomScale
  src/core.js
  test/specs/api.spec.js
Labels: bug

#890 chore: add sample for rejecting drag start outside chartArea
  docs/.vuepress/config.js
  docs/samples/drag/reject-outside.md
  src/hammer.js
Labels: documentation

#891 fix: filter only one click after drag/pan is completed
  src/hammer.js
  src/handlers.js
  src/plugin.js
Labels: bug

#896 Clamp drag rectangle to chart area
  src/handlers.js
  test/specs/zoom.drag.spec.js
Labels: bug

#898 Fix handling at canvas edge
  src/handlers.js
  test/specs/zoom.drag.spec.js
Labels: bug

#900 Fixes to types and spelling
  MAINTAINING.md
  docs/guide/options.md
  docs/samples/wheel/click-zoom.md
  types/options.d.ts
Labels: documentation, types

#902 Switch coverallsapp action to use a tag version instead of deprecated master branch
  .github/workflows/ci.yml
Labels: infrastructure

#905 fix: pinch events
  src/hammer.js
  test/specs/zoom.pinch.spec.js
Labels: bug

#901 feat: add trigger to onZoom context
  src/core.js
  src/hammer.js
  src/handlers.js
  src/state.js
  test/specs/api.spec.js
  test/specs/zoom.drag.spec.js
  test/specs/zoom.wheel.spec.js
  types/index.d.ts
  types/options.d.ts
Labels: enhancement
